name: Deploy Docs

on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # clone 源码到工作流中
      - uses: actions/checkout@v4
      # 安装 node 环境
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build VuePress
        run: yarn docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
